# Generated by Django 6.0.4 on 2026-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('data_nascimento', models.CharField(verbose_name='Data de Nascimento')),
            ],
        ),
    ]
